### ISSUE TITLE
0.14.1 doesn't compile

### ISSUE THREAD

**Issue by antonio-rojas** [jupyter-widgets-contrib/ipycanvas#372]
Getting a compilation error with 0.14.1:
```
INFO:hatch_jupyter_builder.utils:> /usr/bin/yarn run build:extensions
yarn run v1.22.22
$ yarn run build && yarn run build:labextension
$ yarn run build:lib && yarn run build:nbextension && yarn run build:labextension
$ tsc
src/utils.ts(142,26): error TS2322: Type 'Uint8ClampedArray<ArrayBufferLike>' is not assignable to type 'BlobPart'.
  Type 'Uint8ClampedArray<ArrayBufferLike>' is not assignable to type 'ArrayBufferView<ArrayBuffer>'.
    Types of property 'buffer' are incompatible.
      Type 'ArrayBufferLike' is not assignable to type 'ArrayBuffer'.
        Type 'SharedArrayBuffer' is not assignable to type 'ArrayBuffer'.
          Types of property '[Symbol.toStringTag]' are incompatible.
            Type '"SharedArrayBuffer"' is not assignable to type '"ArrayBuffer"'.
error Command failed with exit code 1.
```

**Comment by antonio-rojas** [comment]
Thanks, works fine with yarn 4.9.2
